models:
  llama:
    - name: "Llama 3 Groq 70B Tool Use (Preview)"
      id: "llama3-groq-70b-8192-tool-use-preview"
    - name: "Llama 3 Groq 8B Tool Use (Preview)"
      id: "llama3-groq-8b-8192-tool-use-preview"
    - name: "Llama 3.1 70B"
      id: "llama-3.1-70b-versatile"
    - name: "Llama 3.1 8B"
      id: "llama-3.1-8b-instant"
    - name: "Llama 3.2 1B (Preview)"
      id: "llama-3.2-1b-preview"
    - name: "Llama 3.2 3B (Preview)"
      id: "llama-3.2-3b-preview"
    - name: "Llama 3.2 11B Vision (Preview)"
      id: "llama-3.2-11b-vision-preview"
    - name: "Llama 3.2 90B (Preview)"
      id: "llama-3.2-90b-vision-preview"
    - name: "Meta Llama 3 70B"
      id: "llama3-70b-8192"
    - name: "Meta Llama 3 8B"
      id: "llama3-8b-8192"

  mistral:
    - name: "Mixtral 8x7B"
      id: "mixtral-8x7b-32768"

  gemma:
    - name: "Gemma 2 9B"
      id: "gemma2-9b-it"
    - name: "Gemma 7B"
      id: "gemma-7b-it"

  distil_whisper:
    - name: "Distil-Whisper English"
      id: "distil-whisper-large-v3-en"
    - name: "Whisper Large V3"
      id: "whisper-large-v3"
    - name: "Whisper Large V3 Turbo"
      id: "whisper-large-v3-turbo"
